package land.temmi.rollercoaster.world;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.TextureRegion;

/**
 * Appearance and walkability of one tile type.
 *
 * <p>Terrain geometry is generated by {@link ChunkMesher} from the map's heights and shapes, so a
 * tile type only describes how its top and its exposed sides look. Sides fall back to the top
 * appearance, which keeps simple tilesets to one region per tile.
 */
public final class TileSurface {
    public final String id;
    public final Color topColor = new Color(Color.WHITE);
    public final Color sideColor = new Color(Color.WHITE);

    private final float[] topUv = {0f, 0f, 1f, 1f};
    private final float[] sideUv = {0f, 0f, 1f, 1f};
    private boolean walkable = true;

    public TileSurface(String id) {
        if (id == null || id.length() == 0) throw new IllegalArgumentException("Tile id is required");
        this.id = id;
    }

    public TileSurface setColor(Color top, Color side) {
        if (top == null || side == null) throw new IllegalArgumentException("Tile colors are required");
        topColor.set(top);
        sideColor.set(side);
        return this;
    }

    /** Tints the sides by a factor of the top colour, the usual way to read a cliff as shaded. */
    public TileSurface setColor(Color top, float sideTint) {
        if (top == null || sideTint < 0f) throw new IllegalArgumentException("Invalid tile color");
        topColor.set(top);
        sideColor.set(top.r * sideTint, top.g * sideTint, top.b * sideTint, top.a);
        return this;
    }

    public TileSurface setRegion(TextureRegion top, TextureRegion side) {
        if (top == null) throw new IllegalArgumentException("Top region is required");
        setUv(topUv, top);
        setUv(sideUv, side == null ? top : side);
        return this;
    }

    /** A non-walkable ramp still slopes; it is scenery no actor may step onto. */
    public TileSurface setWalkable(boolean walkable) {
        this.walkable = walkable;
        return this;
    }

    public boolean isWalkable() { return walkable; }

    float topU() { return topUv[0]; }
    float topV() { return topUv[1]; }
    float topU2() { return topUv[2]; }
    float topV2() { return topUv[3]; }
    float sideU() { return sideUv[0]; }
    float sideV() { return sideUv[1]; }
    float sideU2() { return sideUv[2]; }
    float sideV2() { return sideUv[3]; }

    private static void setUv(float[] target, TextureRegion region) {
        target[0] = region.getU();
        target[1] = region.getV();
        target[2] = region.getU2();
        target[3] = region.getV2();
    }
}
